# Generated by Django 4.1.6 on 2025-07-24 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Pessoa Física'), (1, 'Pessoa Jurídica')], default=0, verbose_name='Tipo')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Status do Cadastro')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('pessoa_juridica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('is_estadual', models.CharField(blank=True, max_length=14, null=True, verbose_name='Incrição Estadual')),
                ('is_municipal', models.CharField(blank=True, max_length=14, null=True, verbose_name='Incrição Municipal')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('cnpj_situacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Situação')),
                ('cnpj_porte', models.CharField(blank=True, max_length=200, null=True, verbose_name='Porte de Empresa')),
                ('cnpj_data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('cnpj_tipo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo')),
                ('cnpj_atividade_principal', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Atividade Principal')),
                ('primeiro_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('ultimo_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG (legado)')),
                ('rg_emissor', models.CharField(blank=True, max_length=3, null=True, verbose_name='Emissor')),
                ('rg_expedicao', models.DateField(blank=True, null=True, verbose_name='Expedicao')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('escolaridade', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sem Ensino'), (2, 'Fundamental - Incompleto'), (3, 'Fundamental - Completo'), (4, 'Médio - Incompleto'), (5, 'Médio - Completo'), (6, 'Superior - Incompleto'), (7, 'Superior - Completo'), (8, 'Pós-graduação (Lato senso) - Incompleto'), (9, 'Pós-graduação (Lato senso) - Completo'), (10, 'Pós-graduação (Stricto sensu, nível mestrado) - Incompleto'), (11, 'Pós-graduação (Stricto sensu, nível mestrado) - Completo'), (12, 'Pós-graduação (Stricto sensu, nível doutor) - Incompleto'), (13, 'Pós-graduação (Stricto sensu, nível doutor) - Completo')], null=True, verbose_name='Escolaridade')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros'), ('-', 'Não Informado')], max_length=1, null=True, verbose_name='Sexo')),
                ('estado_civil', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Casado'), (2, 'Divorciado'), (3, 'Solteiro'), (4, 'União Estavel'), (5, 'Viúvo')], null=True, verbose_name='Estado Civil')),
                ('conjuge_primeiro_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Conjuge')),
                ('conjuge_ultimo_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome do Conjuge')),
                ('mae_primeiro_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Mãe')),
                ('mae_ultimo_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome da Mãe')),
                ('pai_primeiro_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Pai')),
                ('pai_ultimo_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome do Pai')),
                ('obs_pessoal', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações')),
                ('cnh_n', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNH')),
                ('cnh_emissao', models.DateField(blank=True, null=True, verbose_name='Emissão')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('cnh_categoria', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'AB'), (4, 'C'), (5, 'D'), (6, 'E')], null=True, verbose_name='Categoria')),
                ('email_1', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('email_2', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('fone_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato')),
                ('fone_1_tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 01 Tipo')),
                ('fone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato')),
                ('fone_2_tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 02 Tipo')),
                ('fone_3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato')),
                ('fone_3_tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 03 Tipo')),
                ('link_1', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('link_2', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('obs_contato', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço')),
                ('numero', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=250, null=True, verbose_name='Complemento')),
                ('obs_endereco', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações')),
                ('ultima_att', models.CharField(blank=True, max_length=200, null=True, verbose_name='Última Atualização')),
                ('data_att', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização')),
                ('nome_razao_titular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome/Razão')),
                ('tipo_de_documento', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'CPF'), (1, 'CNPJ')], null=True, verbose_name='Tipo de Documento')),
                ('documento_titular', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('tipo_de_conta', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Conta Corrente'), (2, 'Conta Salário'), (3, 'Conta Poupança')], null=True, verbose_name='Tipo de Conta')),
                ('n_banco', models.IntegerField(blank=True, default=0, null=True, verbose_name='N° Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Conta')),
                ('digito', models.CharField(blank=True, max_length=5, null=True, verbose_name='Dígito')),
                ('pix_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave PIX')),
                ('pix_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave PIX')),
                ('obs_banco', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações')),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
        ),
    ]
