# Generated by Django 4.1.6 on 2023-03-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_empresa',
            name='cnpj_atividade_principal',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Atividade Principal'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='cnpj_data_abertura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='cnpj_porte',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Porte de Empresa'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='cnpj_situacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='cnpj_tipo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Status do Cadastro'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1, verbose_name='Status do Cadastro'),
        ),
    ]
