# Generated by Django 5.2.4 on 2025-08-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_historicalcadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='data_att',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='ultima_att',
        ),
        migrations.RemoveField(
            model_name='historicalcadastro',
            name='data_att',
        ),
        migrations.RemoveField(
            model_name='historicalcadastro',
            name='ultima_att',
        ),
    ]
