# Generated by Django 4.1.6 on 2023-05-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cadastro_empresa_cnpj_data_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_empresa',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='conta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Conta'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='digito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Digito'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='documento_titular',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='n_banco',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='N° Banco'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='nome_razao_titular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome/Razão'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='obs_banco',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='pix_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PIX'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='pix_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PIX'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='tipo_de_conta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Conta Corrente'), (2, 'Conta Salário'), (3, 'Conta Poupança')], null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CPF'), (2, 'CNPJ')], null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='conta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Conta'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='digito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Digito'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='documento_titular',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='n_banco',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='N° Banco'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='nome_razao_titular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome/Razão'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='obs_banco',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='pix_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PIX'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='pix_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PIX'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='tipo_de_conta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Conta Corrente'), (2, 'Conta Salário'), (3, 'Conta Poupança')], null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CPF'), (2, 'CNPJ')], null=True, verbose_name='Tipo de Documento'),
        ),
    ]
