# Generated by Django 5.2.5 on 2025-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_cadastro_data_att_remove_cadastro_ultima_att_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG (Descontinuado)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Status do Cadastro'),
        ),
        migrations.AlterField(
            model_name='historicalcadastro',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG (Descontinuado)'),
        ),
        migrations.AlterField(
            model_name='historicalcadastro',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Status do Cadastro'),
        ),
    ]
