# Generated by Django 4.1.6 on 2023-05-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_cadastro_empresa_agencia_cadastro_empresa_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='digito',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Digito'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='digito',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Digito'),
        ),
    ]
