# Generated by Django 4.1.6 on 2023-05-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_cadastro_empresa_agencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='tipo_de_conta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Conta Corrente'), (2, 'Conta Salário'), (3, 'Conta Poupança')], default=0, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'CPF'), (1, 'CNPJ')], null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'CPF'), (1, 'CNPJ')], default=0, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
