# Generated by Django 4.1.6 on 2023-05-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_cadastro_empresa_tipo_de_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='digito',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dígito'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='documento_titular',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='email_1',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='email_2',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='fone_1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='fone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='fone_3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='link_1',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='link_2',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='pix_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='pix_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='tipo_de_conta',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Conta Corrente'), (2, 'Conta Salário'), (3, 'Conta Poupança')], null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'CPF'), (1, 'CNPJ')], default=0, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='digito',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dígito'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='documento_titular',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='email_1',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='email_2',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='fone_1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='fone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='fone_3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='link_1',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='link_2',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='pix_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='pix_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave PIX'),
        ),
    ]
