# Generated by Django 4.1.6 on 2023-06-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_cadastro_empresa_digito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='cnh_categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'AB'), (4, 'C'), (4, 'D'), (4, 'E')], default=1, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='cnh_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='cnh_n',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='cnh_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='fone_1_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 01 Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='fone_2_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 02 Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='fone_3_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 03 Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'CPF'), (1, 'CNPJ')], null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='fone_1_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 01 Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='fone_2_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 02 Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='fone_3_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telefone'), (2, 'WhatsApp')], null=True, verbose_name='Contato 03 Tipo'),
        ),
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='tipo_de_documento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'CPF'), (1, 'CNPJ')], null=True, verbose_name='Tipo de Documento'),
        ),
    ]
