# Generated by Django 4.1.6 on 2023-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_cadastro_pessoa_cnh_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='cnh_n',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CNH'),
        ),
    ]
