# Generated by Django 4.1.6 on 2023-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_cadastro_pessoa_cnh_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='cnh_categoria',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'AB'), (4, 'C'), (5, 'D'), (6, 'E')], null=True, verbose_name='Categoria'),
        ),
    ]
