# Generated by Django 4.1.6 on 2025-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_cadastro_pessoa_cnh_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros'), ('-', 'Não Informado')], default=1, max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
