# Generated by Django 4.1.6 on 2025-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_cadastro_remove_cadastro_pessoa_cadastrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pessoa Física'), (1, 'Pessoa Jurídica')], default=0, verbose_name='Tipo'),
        ),
    ]
