# Generated by Django 4.1.6 on 2025-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_cadastro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros'), ('-', 'Não Informado')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
