# Generated by Django 5.2.5 on 2026-01-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregister',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Homem cisgênero'), ('MT', 'Homem transgênero'), ('F', 'Mulher cisgênero'), ('FT', 'Mulher transgênero'), ('NF', 'Pessoa não binária do sexo feminino'), ('NM', 'Pessoa não binária do sexo masculino'), ('-', 'Não informado')], max_length=2, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='register',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Homem cisgênero'), ('MT', 'Homem transgênero'), ('F', 'Mulher cisgênero'), ('FT', 'Mulher transgênero'), ('NF', 'Pessoa não binária do sexo feminino'), ('NM', 'Pessoa não binária do sexo masculino'), ('-', 'Não informado')], max_length=2, null=True, verbose_name='Sexo'),
        ),
    ]
